# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.
[tools]
# build system
rojo = "rojo-rbx/rojo@7.3.0"
lune = "lune-org/lune@0.8.2"
rbxcloud = "Sleitnick/rbxcloud@0.14.0"

# for managing dependency libraries
wally = "upliftgames/wally@0.3.2"

# for code analysis
selene = "kampfkarren/selene@0.26.1"
stylua = "johnnymorganz/stylua@0.20.0"

# for image uploading
tarmac = "jeparlefrancais/tarmac@0.7.1"

# for managing the codebase
rit = "esocietyhere/rit@0.6.0"

# for unit testing
run-in-roblox = "rojo-rbx/run-in-roblox@0.3.0"
