title = "The Known Tools"                                  # From Git
gitRepoUrl = "https://github.com/The-Known-Galaxy/plugins" # From Git

gitSourceBranch = "main"
changelog = true
apiCategories = ["constructor", "utility", "methods"]

[[classOrder]]
section = "Plugin Architecture"
classes = ["PluginFacade", "PluginSubModule", "SubModuleManager"]
collapsed = true

[[classOrder]]
section = "Plugin Sub-Modules"
classes = [
    "HiltSetProcessor",
    "DummyPluginModule",
    "ComponentVisualiser",
    "ArchiveValidator",
]
collapsed = false

[[classOrder]]
section = "Utilities"
classes = [
    "Logger",
    "Permissions",
    "NextId",
    "TextFormat",
    "ImportHilt",
    "MaterialManager",
    "ConfigureHilt",
    "Colour",
    "HiltValidator",
    "HiltValidations",
    "VisualiseHilt",
    "NamedAreaVisualiser",
]
collapsed = true

[[classOrder]]
section = "Data Modules"
classes = ["GroupIds", "RankData", "HiltMaterials"]
collapsed = true

[[classOrder]]
section = "User Interface"
classes = [
    "InterfaceConfig",
    "PluginWidgetFrame",
    "ScrollingList",
    "Button",
    "Panel",
    "Text",
    "Padding",
    "ButtonMask",
]
collapsed = true

autoSectionPath = "src"

[docusaurus]
favicon = "assets/images/sienartech_notext.png"

# From git:
organizationName = "The Known Galaxy"
projectName = "The Known Tools"
url = "https://the-known-galaxy.github.io/"
baseUrl = "/plugins"
tagline = "The Known Galaxy's Plugin of Plugins"

[docusaurus.themeConfig.colorMode]
defaultMode = "dark"


[[navbar.items]]
href = "https://create.roblox.com/store/asset/16915363791/TKG-The-Known-Tools"
label = "Plugin"
position = "right"

[home]
enabled = true
includeReadme = true

[[home.features]]
title = "Centralised"
description = "All of TKG's custom Studio plugins are centralised in this one plugin. Every possible developer tool or utility made to be used in Studio is written, maintained and managed from this repository."

[[home.features]]
title = "Easy to Expand"
description = "Every plugin inside this repository (called \"Sub-Module\") can be developed completely independently from the others. With a first-class development experience encompassing Hot Reloading and a codebase manager, tools for TKG developers can be made fast and on the fly."

[[home.features]]
title = "Well Documented"
description = "Almost all parts of the inner workings of these plugins are documented on this site. If there's some niche part of a plugin's internal functionality you're curious about, then it's written here."

[footer]
style = "dark"
copyright = "Copyright © 2024 The Known Galaxy. Built with Moonwave and Docusaurus"
