[package]
name = "tkg/plugins"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
# utilities
t = "osyrisrblx/t@3.0.0"
Janitor = "howmanysmall/janitor@1.15.7"
Promise = "evaera/promise@4.0.0"
Signal = "sleitnick/signal@2.0.1"

# data management
Immut = "solarhorizon/immut@0.4.4"
Llama = "freddylist/llama@1.1.1"

# unit testing
TestEZ = "roblox/testez@0.4.1"

# react - these should be updated by version number TOGETHER
react-roblox = "jsdotlua/react-roblox@17.1.0"
react = "jsdotlua/react@17.1.0"
